services:
  django:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod

  fastapi:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod

  nginx:
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped
