# Generated by Django 5.2.14 on 2026-05-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_length', models.CharField(blank=True, choices=[('short', 'short'), ('medium', 'medium'), ('long', 'long'), ('extra_long', 'extra_long')], max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services_catalog.service')),
            ],
            options={
                'verbose_name': 'preço de serviço',
                'verbose_name_plural': 'preços de serviço',
                'indexes': [models.Index(fields=['service', 'hair_length'], name='pricing_ser_service_4c9521_idx')],
            },
        ),
    ]
