# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceSimulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_slug", models.SlugField(max_length=160)),
                ("service_name", models.CharField(max_length=140)),
                ("hair_length", models.CharField(blank=True, max_length=20)),
                ("volume", models.CharField(blank=True, max_length=40)),
                ("goal", models.CharField(blank=True, max_length=80)),
                ("estimated_price", models.CharField(blank=True, max_length=80)),
                ("source", models.CharField(default="price_experience", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "simulação de preço",
                "verbose_name_plural": "simulações de preço",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at", "service_slug"], name="pricing_pri_created_996b93_idx"),
                    models.Index(fields=["hair_length", "created_at"], name="pricing_pri_hair_le_581867_idx"),
                ],
            },
        ),
    ]
