# Generated by Django 5.2.14 on 2026-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('quick', 'Serviços rápidos'), ('finishing', 'Finalização'), ('treatment', 'Tratamentos'), ('chemical', 'Químicas'), ('transformation', 'Transformações')], max_length=40)),
                ('short_description', models.CharField(blank=True, max_length=240)),
                ('long_description', models.TextField(blank=True)),
                ('price_mode', models.CharField(choices=[('fixed', 'fixed'), ('by_length', 'by_length'), ('evaluation', 'evaluation'), ('range', 'range')], max_length=20)),
                ('requires_evaluation', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ['category', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category', 'sort_order'], name='services_ca_is_acti_73fe09_idx')],
            },
        ),
    ]
