from decimal import Decimal

INITIAL_SERVICES = [
    {
        "name": "Lavagem especial",
        "slug": "lavagem-especial",
        "category": "quick",
        "price_mode": "fixed",
        "short_description": "Higienização cuidadosa com acabamento de salão.",
        "is_featured": True,
        "prices": [{"price": Decimal("15.00")}],
    },
    {
        "name": "Corte",
        "slug": "corte",
        "category": "quick",
        "price_mode": "fixed",
        "short_description": "Corte com leitura de formato, textura e caimento.",
        "is_featured": True,
        "prices": [{"price": Decimal("25.00"), "label": "A partir de"}],
    },
    {
        "name": "Escova",
        "slug": "escova",
        "category": "finishing",
        "price_mode": "by_length",
        "short_description": "Finalização polida com brilho, alinhamento e movimento.",
        "is_featured": True,
        "prices": [
            {"hair_length": "short", "price": Decimal("20.00")},
            {"hair_length": "medium", "price": Decimal("25.00")},
            {"hair_length": "long", "price": Decimal("30.00")},
            {"hair_length": "extra_long", "price": Decimal("35.00")},
        ],
    },
    {
        "name": "Prancha",
        "slug": "prancha",
        "category": "finishing",
        "price_mode": "by_length",
        "short_description": "Acabamento térmico controlado para fios alinhados.",
        "prices": [
            {"hair_length": "short", "price": Decimal("20.00")},
            {"hair_length": "medium", "price": Decimal("25.00")},
            {"hair_length": "long", "price": Decimal("30.00")},
            {"hair_length": "extra_long", "price": Decimal("35.00")},
        ],
    },
    {
        "name": "Escova + prancha",
        "slug": "escova-prancha",
        "category": "finishing",
        "price_mode": "by_length",
        "short_description": "Pacote de finalização com polimento intenso.",
        "is_featured": True,
        "prices": [
            {"hair_length": "short", "price": Decimal("25.00")},
            {"hair_length": "medium", "price": Decimal("30.00")},
            {"hair_length": "long", "price": Decimal("35.00")},
            {"hair_length": "extra_long", "price": Decimal("45.00")},
        ],
    },
    {
        "name": "Tranças",
        "slug": "trancas",
        "category": "finishing",
        "price_mode": "evaluation",
        "requires_evaluation": True,
        "short_description": "Produção personalizada conforme estilo, técnica e volume.",
        "prices": [],
    },
    {
        "name": "Fitagem",
        "slug": "fitagem",
        "category": "finishing",
        "price_mode": "evaluation",
        "requires_evaluation": True,
        "short_description": "Definição de cachos com leitura de curvatura e densidade.",
        "prices": [],
    },
    {
        "name": "Penteados",
        "slug": "penteados",
        "category": "transformation",
        "price_mode": "evaluation",
        "requires_evaluation": True,
        "short_description": "Composições para eventos, fotos e ocasiões especiais.",
        "prices": [],
    },
    {
        "name": "Coloração",
        "slug": "coloracao",
        "category": "chemical",
        "price_mode": "fixed",
        "short_description": "Aplicação técnica com atenção ao histórico capilar.",
        "prices": [{"price": Decimal("25.00")}],
    },
    {
        "name": "Pintura",
        "slug": "pintura",
        "category": "chemical",
        "price_mode": "fixed",
        "short_description": "Cobertura e manutenção de cor com acabamento profissional.",
        "prices": [{"price": Decimal("20.00")}],
    },
    {
        "name": "Morena iluminada",
        "slug": "morena-iluminada",
        "category": "chemical",
        "price_mode": "by_length",
        "requires_evaluation": True,
        "is_featured": True,
        "short_description": "Iluminação estratégica para contraste elegante e natural.",
        "prices": [
            {"hair_length": "short", "price": Decimal("130.00")},
            {"hair_length": "medium", "price": Decimal("180.00")},
            {"hair_length": "long", "price": Decimal("200.00")},
            {"hair_length": "extra_long", "price": Decimal("250.00")},
        ],
    },
    {
        "name": "Luzes / mechas",
        "slug": "luzes-mechas",
        "category": "chemical",
        "price_mode": "by_length",
        "requires_evaluation": True,
        "is_featured": True,
        "short_description": "Técnica de clareamento com diagnóstico e refinamento de tom.",
        "prices": [
            {"hair_length": "short", "price": Decimal("150.00")},
            {"hair_length": "medium", "price": Decimal("200.00")},
            {"hair_length": "long", "price": Decimal("250.00")},
            {"hair_length": "extra_long", "price": Decimal("300.00")},
        ],
    },
    {
        "name": "Selagem orgânica",
        "slug": "selagem-organica",
        "category": "chemical",
        "price_mode": "by_length",
        "requires_evaluation": True,
        "short_description": "Alinhamento com acabamento disciplinado e toque sofisticado.",
        "prices": [
            {"hair_length": "short", "price": Decimal("130.00")},
            {"hair_length": "medium", "price": Decimal("160.00")},
            {"hair_length": "long", "price": Decimal("200.00")},
            {"hair_length": "extra_long", "price": Decimal("250.00")},
        ],
    },
    {
        "name": "Selagem",
        "slug": "selagem",
        "category": "chemical",
        "price_mode": "by_length",
        "short_description": "Controle de frizz e alinhamento conforme estrutura do fio.",
        "prices": [
            {"hair_length": "short", "price": Decimal("130.00")},
            {"hair_length": "medium", "price": Decimal("150.00")},
            {"hair_length": "long", "price": Decimal("180.00")},
            {"hair_length": "extra_long", "price": Decimal("200.00")},
        ],
    },
    {
        "name": "Definitiva Of Gold",
        "slug": "definitiva-of-gold",
        "category": "chemical",
        "price_mode": "by_length",
        "requires_evaluation": True,
        "short_description": "Procedimento técnico com avaliação de resistência e histórico.",
        "prices": [
            {"hair_length": "short", "price": Decimal("150.00")},
            {"hair_length": "medium", "price": Decimal("200.00")},
            {"hair_length": "long", "price": Decimal("250.00")},
            {"hair_length": "extra_long", "price": Decimal("300.00")},
        ],
    },
    {
        "name": "Progressiva",
        "slug": "progressiva",
        "category": "chemical",
        "price_mode": "by_length",
        "requires_evaluation": True,
        "short_description": "Alisamento e redução de volume com análise prévia do fio.",
        "prices": [
            {"hair_length": "short", "price": Decimal("150.00")},
            {"hair_length": "medium", "price": Decimal("200.00")},
            {"hair_length": "long", "price": Decimal("250.00")},
            {"hair_length": "extra_long", "price": Decimal("300.00")},
        ],
    },
]

TREATMENT_SERVICES = [
    ("APIOS SOS", "apios-sos", "50.00"),
    ("BRAÉ Divine ou BRAÉ Revival", "brae-divine-revival", "80.00"),
    ("Hobety Banho de Ouro", "hobety-banho-de-ouro", "60.00"),
    ("Hobety Hidratação", "hobety-hidratacao", "50.00"),
    ("Hobety Rose Gold", "hobety-rose-gold", "60.00"),
    ("Joico Moisture Recovery", "joico-moisture-recovery", "80.00"),
    ("Joico Defy Damage", "joico-defy-damage", "80.00"),
    ("Joico K-PAK", "joico-k-pak", "80.00"),
    ("Keranza Hidratação Intensa", "keranza-hidratacao-intensa", "60.00"),
    ("Keranza Nutrição", "keranza-nutricao", "60.00"),
    ("MDK Hidratação Prime", "mdk-hidratacao-prime", "40.00"),
    ("MDK Hidratação Argan", "mdk-hidratacao-argan", "40.00"),
    ("MDK Cronograma Capilar", "mdk-cronograma-capilar", "130.00"),
    ("Olenka Especialidades", "olenka-especialidades", "70.00"),
    ("Olenka Men's Care Detox Capilar", "olenka-mens-care-detox-capilar", "70.00"),
    ("Rêve Active Color", "reve-active-color", "60.00"),
    ("Rêve Cronograma Capilar", "reve-cronograma-capilar", "150.00"),
    ("Rêve Lótus Flower", "reve-lotus-flower", "150.00"),
    ("Rêve Terapia TRI-TR2", "reve-terapia-tri-tr2", "70.00"),
    ("Smooth Line", "smooth-line", "70.00"),
    ("Wella Invigo Nutrição", "wella-invigo-nutricao", "60.00"),
    ("Wella Fusion Reconstrução", "wella-fusion-reconstrucao", "70.00"),
]

INITIAL_SERVICES.extend(
    {
        "name": name,
        "slug": slug,
        "category": "treatment",
        "price_mode": "fixed",
        "short_description": "Tratamento profissional com indicação conforme diagnóstico capilar.",
        "is_featured": slug in {"brae-divine-revival", "reve-cronograma-capilar"},
        "prices": [{"price": Decimal(price)}],
    }
    for name, slug, price in TREATMENT_SERVICES
)

INITIAL_SERVICES.append(
    {
        "name": "Cronograma Joico",
        "slug": "cronograma-joico",
        "category": "treatment",
        "price_mode": "range",
        "short_description": "Cronograma premium com etapas combinadas conforme diagnóstico.",
        "is_featured": True,
        "prices": [{"min_price": Decimal("200.00"), "max_price": Decimal("220.00")}],
    }
)
