# Generated by Django 5.2.14 on 2026-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('blonde', 'Loiros'), ('brunette', 'Morenos'), ('illuminated_brunette', 'Morenos iluminados'), ('red_hair', 'Ruivos'), ('treatment', 'Tratamentos'), ('finishing', 'Finalizações'), ('before_after', 'Antes e depois'), ('kids', 'Kids'), ('product', 'Produtos profissionais')], max_length=40)),
                ('image', models.ImageField(upload_to='gallery/original/')),
                ('alt_text', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('client_authorized', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'imagem da galeria',
                'verbose_name_plural': 'imagens da galeria',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('indication', models.CharField(blank=True, max_length=180)),
                ('expected_result', models.CharField(blank=True, max_length=180)),
                ('premium_score', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'linha de produto',
                'verbose_name_plural': 'linhas de produto',
                'ordering': ['brand', 'name'],
            },
        ),
    ]
