# Generated by Django 5.2.14 on 2026-05-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('whatsapp', models.CharField(max_length=32)),
                ('hair_length', models.CharField(blank=True, max_length=20)),
                ('chemical_history', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contato feito'), ('scheduled', 'Agendado'), ('cancelled', 'Cancelado'), ('done', 'Atendido')], default='new', max_length=20)),
                ('consent_privacy_policy', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('desired_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services_catalog.service')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
