# Generated by Django 5.2.14 on 2026-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=260)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('is_indexable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'página SEO',
                'verbose_name_plural': 'páginas SEO',
                'ordering': ['path'],
            },
        ),
    ]
