# Generated by Django 5.2.14 on 2026-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slogan', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('instagram_url', models.URLField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('primary_logo', models.ImageField(blank=True, null=True, upload_to='brand/logo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'perfil de marca',
                'verbose_name_plural': 'perfis de marca',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
